// <auto-generated />
namespace Corgr_Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20160727342pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160727342pm));
        
        string IMigrationMetadata.Id
        {
            get { return "201607271242421_20160727342pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
